#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

## Kill if already running
#killall -9 xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager
killall -9 xfsettingsd picom polybar dunst xfce4-power-manager

## xfce4-settings daemon
xfsettingsd &

## Enable Super Keys For Menu
#ksuperkey -e 'Super_L=Alt_L|F1' &
#ksuperkey -e 'Super_R=Alt_L|F1' &

## Restore Wallpaper
nitrogen --restore &



## polkit agent
#if [[ ! `pidof xfce-polkit` ]]; then
#	/usr/lib/xfce-polkit/xfce-polkit &
#fi

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom &

## Launch Polybar or Tint2
exec polybar -r &

## Notification Daemon
exec dunst &

## Launch Plank
exec plank &

## Thunar Daemon
exec thunar --daemon &

## These applets are specifically for tint2 panel.
## If you're using tint2 as panel, Uncomment these applets.

## User Friendly Network Menu
nm-applet --indicator &

## User Friendly Bluetooth Menu
blueman-applet &

