#!/usr/bin/env bash

## Kill if already running
killall -9 xfsettingsd polybar dunst xfce4-power-manager

## xfce4-settings daemon
xfsettingsd &

## Restore Wallpaper
nitrogen --restore &

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec nippy-compositor start &

## Launch Polybar
exec polybar -r &

## Notification Daemon
exec dunst &

## Launch Plank
exec plank &

## Clipboard Manager
nippy-clippy --daemon

## Thunar Daemon
exec thunar --daemon &

## User Friendly Network Menu
nm-applet --indicator &

## User Friendly Bluetooth Menu
blueman-applet &
