#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
## Modificado por Rapoelho, para incluir a opção desse Script ser um Pipemenu e para uso no Nippybox
## Script to take screenshots on Archcraft.

# pipemenu
pipemenu () {
	MENUS_LIBDIR="$HOME/.config/openbox/"
	if ! source "$MENUS_LIBDIR/pipebase.cfg" 2> /dev/null; then
		echo $"Error: Failed to locate pipebase.cfg in $MENUS_LIBDIR" >&2
		exit 1
	fi

	menuStart
		menuSeparator 'Fullscreen'
		menuItem 'Screenshot Now' "$0 --now"
		menuItem 'Screenshot In 5s' "$0 --in5"
		menuItem 'Screenshot In 10s' "$0 --in10"
		menuSeparator 'Area'
		menuItem 'Screenshot Area' "$0 --area"
		menuItem 'Screenshot Window' "$0 --win"
	menuEnd
}

# file
time=`date +%Y-%m-%d-%H-%M-%S`
geometry=`xrandr | grep 'current' | head -n1 | cut -d',' -f2 | tr -d '[:blank:],current'`
dir="`xdg-user-dir PICTURES`/Screenshots"
file="Screenshot_${time}_${geometry}.png"
border='0.000,0.735,0.832'

# directory
if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

# notify and view screenshot
notify_view () {
	notify_cmd_shot='dunstify -u low -h string:x-dunst-stack-tag:obscreenshot'
	paplay /usr/share/sounds/freedesktop/stereo/screen-capture.oga &>/dev/null &
	${notify_cmd_shot} "Screenshot Saved."
}

# copy screenshot to clipboard
copy_shot () {
	tee "$file" | xclip -selection clipboard -t image/png
}

# countdown
countdown () {
	for sec in `seq $1 -1 1`; do
		dunstify -t 1000 -h string:x-dunst-stack-tag:screenshottimer "Taking shot in : $sec"
		sleep 1
	done
}

# take shots
shotnow () {
	cd ${dir} && maim -f png | copy_shot
	notify_view
}

shot5 () {
	countdown '5'
	sleep 1 && cd ${dir} && maim -f png | copy_shot
	notify_view
}

shot10 () {
	countdown '10'
	sleep 1 && cd ${dir} && maim -f png | copy_shot
	notify_view
}

shotwin () {
	cd ${dir} && maim -f png -i `xdotool getactivewindow` | copy_shot
	notify_view
}

shotarea () {
	cd ${dir} && maim -f png -s -b 2 -c ${border},0.25 -l | copy_shot
	notify_view
}

# execute
if [[ "$1" == "--now" ]]; then
	shotnow
elif [[ "$1" == "--in5" ]]; then
	shot5
elif [[ "$1" == "--in10" ]]; then
	shot10
elif [[ "$1" == "--win" ]]; then
	shotwin
elif [[ "$1" == "--area" ]]; then
	shotarea
elif [[ "$1" == "--pipe" ]]; then
	pipemenu
else
	echo -e "Available Options : --now --in5 --in10 --win --area"
fi

exit 0
