#!/bin/bash

### Variáveis da Polybar
polybarFile="colors.ini"
polybarFolder="$HOME/.config/polybar"

### Variáveis do Dunst
dunstFile="dunstrc"
dusntFolder="$HOME/.config/dunst"

### Variáveis do Rofi
rofiFile="colors.rasi"
rofiFoler="$HOME/.config/rofi/shared"

### Tema Openbox
obThemeFile="themerc"
obThemeName="nippybox"
obThemeFolder="$HOME/.themes/$obThemeName/openbox-3"

file=$HOME/.Xresources

## Obtendo as Cores do Tema
fill_color(){
	get_colors(){
		grep "color$1 *:" $file | awk -F\# '{print $2}' | head -1
	}
	get_colors_bg=`grep "background *:" $file | awk -F\# '{print $2}' | head -1`
	get_colors_fg=`grep "foreground *:" $file | awk -F\# '{print $2}' | head -1`
}

## Função para Colorir a Polybar
poly_color(){
	{
	cat <<EOF
[color]

background = #${get_colors_bg}
foreground = #${get_colors_fg}
foreground-alt = #$(get_colors 8)
module-fg = #F5F5F5
primary = #$(get_colors 1)
secondary = #$(get_colors 2)
alternate = #$(get_colors 3)

EOF
	} > $polybarFile
	mv $polybarFile $polybarFolder
}

## Função para Colorir o dunst
dunst_color(){
	{
	cat <<EOF

[global]

## Display
monitor = 0
follow = mouse
width = 300
height = (0, 300)
origin = top-right
offset = (10, 40)
indicate_hidden = yes
notification_limit = 0
gap_size = 12
padding = 15
horizontal_padding = 15
frame_width = 2
sort = yes

## Progress Bar
progress_bar = true
progress_bar_height = 80
progress_bar_frame_width = 0
progress_bar_min_width = 300
progress_bar_max_width = 300

## Text
font = Iosevka Custom 9
markup = full
format = "<small>%a</small>\n<big><b>%s</b></big>\n%b"
#format = %s\n%b
alignment = left
vertical_alignment = center
show_age_threshold = 60
hide_duplicate_count = false
text_icon_padding = 0

## Icon
icon_position = left
min_icon_size = 32
max_icon_size = 48

## Line and Separator
line_height = 2
separator_height = 2
separator_color = frame

## Misc
corner_radius = 10
scale = 0
idle_threshold = 120
transparency = 0
ellipsize = middle
ignore_newline = no
stack_duplicates = true
show_indicators = yes
enable_recursive_icon_lookup = true
sticky_history = yes
history_length = 20
browser = /usr/bin/xdg-open
always_run_script = true

## Mouse
mouse_left_click = close_current
mouse_middle_click = do_action, close_current
mouse_right_click = close_all

## Advanced
title = Dunst
class = Dunst

[urgency_low]
timeout = 2
background = "#${get_colors_bg}"
foreground = "#${get_colors_fg}"
frame_color = "#$(get_colors 6)"

[urgency_normal]
timeout = 5
background = "#${get_colors_bg}"
foreground = "#${get_colors_fg}"
frame_color = "#$(get_colors 1)"

[urgency_critical]
timeout = 0
background = "#${get_colors_bg}"
foreground = "#$(get_colors 8)"
frame_color = "#$(get_colors 4)"

EOF
	} > $dunstFile
	mv $dunstFile $dusntFolder
	pkill dunst && dunst & > /dev/null
}

## Função para Colorir o Rofi
rofi_color() {
	{
	cat <<EOF
* {
    background:     #${get_colors_bg};
    background-alt: #$(get_colors 7);
    foreground:     #${get_colors_fg};
    selected:       #$(get_colors 4);
    active:         #$(get_colors 6);
    urgent:         #$(get_colors 12);
}
EOF
} > $rofiFile
mv $rofiFile $rofiFoler
}
 
obTheme(){
	{
	cat <<EOF

# Menu
menu.border.width: 10
menu.overlap.x:    -20
menu.overlap.y:    -20

menu.border.color:              #${get_colors_bg}
menu.separator.color:           #${get_colors_bg}

menu.title.bg:                  flat solid
menu.title.bg.color:            #${get_colors_bg}
menu.title.text.color:          #$(get_colors 1)
menu.title.text.justify:        Center

menu.items.bg:                  flat solid
menu.items.bg.color:            #${get_colors_bg}

menu.items.text.color:          #$(get_colors 7)
menu.items.disabled.text.color: #$(get_colors 1)

menu.items.active.bg:           flat solid
menu.items.active.bg.color:     #$(get_colors 4)
menu.items.active.text.color:   #${get_colors_fg}

# Active window
window.active.border.color:                           #$(get_colors 1)

window.active.title.bg:                               solid flat
window.active.title.bg.color:                         #1e1f29
window.active.title.separator.color:                  #1e1f29
window.active.text.justify:                           center

window.active.label.bg:                               parentrelative
window.active.label.text.color:                       #$(get_colors 7)

window.active.handle.bg:                              flat solid
window.active.handle.bg.color:                        #$(get_colors 4)

window.active.grip.bg:                                flat solid
window.active.grip.bg.color:                          #$(get_colors 4)

window.active.button.unpressed.bg:                    parentrelative
window.active.button.unpressed.bg.color:              #${get_colors_bg}

window.active.button.iconify.unpressed.image.color:   #$(get_colors 7)
window.active.button.iconify.pressed.image.color:     #$(get_colors 3)
window.active.button.iconify.hover.image.color:       #$(get_colors 4)

window.active.button.max.unpressed.image.color:       #$(get_colors 7)
window.active.button.max.pressed.image.color:         #$(get_colors 2)
window.active.button.max.hover.image.color:           #$(get_colors 4)

window.active.button.close.unpressed.image.color:     #$(get_colors 7)
window.active.button.close.pressed.image.color:       #$(get_colors 1)
window.active.button.close.hover.image.color:         #$(get_colors 4)

window.active.button.shade.unpressed.image.color:     #$(get_colors 7)
window.active.button.shade.pressed.image.color:       #$(get_colors 5)
window.active.button.shade.hover.image.color:         #$(get_colors 4)

window.active.button.desk.unpressed.image.color:      #$(get_colors 7)
window.active.button.desk.pressed.image.color:        #$(get_colors 6)
window.active.button.desk.hover.image.color:          #$(get_colors 4)

window.active.button.pressed.bg:                      parentrelative
window.active.button.pressed.bg.color:                #$(get_colors 4)

window.active.button.disabled.bg:                     parentrelative
window.active.button.disabled.bg.color:               #${get_colors_bg}
window.active.button.disabled.image.color:            #${get_colors_bg}

window.active.button.toggled.bg:                      parentrelative
window.active.button.toggled.image.color:             #$(get_colors 5)

window.active.button.toggled.pressed.bg:              parentrelative
window.active.button.toggled.pressed.image.color:     #$(get_colors 5)

# Inactive window
window.inactive.border.color:                         #$(get_colors 4)

window.inactive.title.bg:                             flat solid
window.inactive.title.bg.color:                       #1e1f29
window.inactive.title.separator.color:                #1e1f29
window.inactive.text.justify:                         center

window.inactive.label.bg:                             parentrelative
window.inactive.label.text.color:                     #$(get_colors 8)

window.inactive.handle.bg:                            flat solid
window.inactive.handle.bg.color:                      #$(get_colors 5)

window.inactive.grip.bg:                              flat solid
window.inactive.grip.bg.color:                        #$(get_colors 5)

window.inactive.button.unpressed.bg:                  parentrelative
window.inactive.button.unpressed.bg.color:            #${get_colors_bg}

window.inactive.button.iconify.unpressed.image.color: #$(get_colors 8)
window.inactive.button.iconify.pressed.image.color:   #$(get_colors 3)
window.inactive.button.iconify.hover.image.color:     #$(get_colors 15)

window.inactive.button.max.unpressed.image.color:     #$(get_colors 8)
window.inactive.button.max.pressed.image.color:       #$(get_colors 2)
window.inactive.button.max.hover.image.color:         #$(get_colors 15)

window.inactive.button.close.unpressed.image.color:   #$(get_colors 8)
window.inactive.button.close.pressed.image.color:     #$(get_colors 1)
window.inactive.button.close.hover.image.color:       #$(get_colors 15)

window.inactive.button.shade.unpressed.image.color:   #$(get_colors 8)
window.inactive.button.shade.pressed.image.color:     #$(get_colors 5)
window.inactive.button.shade.hover.image.color:       #$(get_colors 15)

window.inactive.button.desk.unpressed.image.color:    #$(get_colors 8)
window.inactive.button.desk.pressed.image.color:      #$(get_colors 6)
window.inactive.button.desk.hover.image.color:        #$(get_colors 15)

window.inactive.button.pressed.bg:                    flat solid
window.inactive.button.pressed.bg.color:              #$(get_colors 4)

window.inactive.button.disabled.bg:                   flat solid
window.inactive.button.disabled.bg.color:             #${get_colors_bg}
window.inactive.button.disabled.image.color:          #${get_colors_bg}

window.inactive.button.toggled.bg:                    parentrelative
window.inactive.button.toggled.image.color:           #$(get_colors 4)

window.inactive.button.toggled.pressed.bg:            parentrelative
window.inactive.button.toggled.pressed.image.color:   #$(get_colors 4)

# OSD
osd.border.width:                    3
osd.border.color:                    #${get_colors_bg}

osd.bg:                              flat solid
osd.bg.color:                        #${get_colors_bg}
osd.label.bg:                        flat solid
osd.label.bg.color:                  #${get_colors_bg}
osd.label.text.color:                #$(get_colors 7)

osd.hilight.bg:                      flat solid
osd.hilight.bg.color:                #$(get_colors 4)

osd.unhilight.bg:                    flat solid
osd.unhilight.bg.color:              #$(get_colors 8)

osd.button.unpressed.bg:             flat border
osd.button.unpressed.bg.color:       #$(get_colors 8)
osd.button.unpressed.*.border.color: #${get_colors_bg}

osd.button.pressed.bg:               flat border
osd.button.pressed.bg.color:         #$(get_colors 8)
osd.button.pressed.*.border.color:   #${get_colors_bg}

osd.button.focused.bg:               flat solid border
osd.button.focused.bg.color:         #${get_colors_bg}
osd.button.focused.*.border.color:   #${get_colors_bg}

osd.button.focused.box.color:        #$(get_colors 4)

# Fonts
window.active.label.text.font:       shadow=n
window.inactive.label.text.font:     shadow=n
menu.items.font:                     shadow=n
menu.title.text.font:                shadow=n

# Everything else
border.width:                2
padding.width:               15
padding.height:              10
window.handle.width:         0
window.client.padding.width: 0
window.label.text.justify:   right

EOF
	} > $obThemeFile
	mv $obThemeFile $obThemeFolder
}

check_theme(){
	if [[ $(cat $HOME/.config/openbox/rc.xml | grep "nippybox") ]]; then
		notify-send "Done. now you can try your theme :)"
		openbox --reconfigure
	fi
}

## Verificando a Entrada do Comando
if [[ -z "$1" ]]; then
	echo "ERRO: Wallpaper não selecionado"
else
	wallpaper="$1"
fi 

## Exibindo a Saída do Comando
echo "## Papel de Parede Selcionado: $wallpaper"

## Aplicando e Salvando o Papel de Parede
echo "## Aplicando Papel de Parede..."
nitrogen --save --set-zoom-fill "$wallpaper" > /dev/null 2>&1

## Extraindo a paleta de Cores
echo "## Extraindo Paleta de Cores..."
wal -q -i "$wallpaper"
cp ~/.cache/wal/colors.Xresources ~/.Xresources

## Executando as Funções
cd ~/.local/bin
fill_color

echo "## Colorindo as Notificações"
dunst_color

echo "## Colorindo a Polybar..."
poly_color

echo "## Colorindo o Rofi..."
rofi_color

echo "## Colorindo o Tema Openbox..."
obTheme

if [[ "$2" == "--no-X11" ]]; then
	echo "Pronto!"
else
	check_theme
	echo "Pronto!"
fi
