#!/usr/bin/env bash
set -x
## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

RASI="$HOME/.config/rofi/colorpicker.rasi"
folderColor="/tmp/colorpicker"

if ! [ -d "$folderColor" ]; then # Verificando se a pasta existe
		mkdir "$folderColor"
fi

getColor () {
	find $folderColor -iname '*.png' > /tmp/colors
}

rofiPick () {
	option1="󰴱 Pick a Color"
	option2=" Clear History"
}

listColor () {
	echo $option1
	getColor
	
	while IFS= read -r color; do
		colorName="$(cat /tmp/colors | grep $color | sed 's#.*/##' | sed 's/\.[^.]*$//')"
		echo -en "$colorName\0icon\x1f$color\n"
	done < /tmp/colors
	
	echo $option2
}

selectColor() {
	color=$(xcolor --format hex --preview-size 255 --scale 10)
	filename="$(echo $color | sed 's/#//g')"
	image="$folderColor/$filename.png"
	
	if [[ "$color" ]]; then
		echo $color | tr -d "\n" | xclip -selection clipboard
		magick -size 48x48 xc:"$color" $image
		dunstify -u low -h string:x-dunst-stack-tag:obcolorpicker -i $image "$color, copied to clipboard."
	fi
}

if [[ "$1" == "picker" ]]; then
	selectColor
elif [[ "$1" == "rofi" ]]; then
	rofiPick
	colorChoose=$(listColor | rofi -dmenu -theme $RASI)
	
	if [[ "$colorChoose" == "$option1" ]]; then
		selectColor
	elif [[ "$colorChoose" == "$option2" ]]; then
		rm $folderColor/*
	else
		echo -e "#$colorChoose" | xclip -selection clipboard
	fi
fi
